# Generated by Django 6.0.7 on 2026-08-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='share_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='share_token',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
