# Generated by Django 6.0.7 on 2026-07-28 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('doc', 'Document'), ('audio', 'Audio'), ('other', 'Other')], max_length=10)),
                ('original_name', models.CharField(max_length=500)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='chat.conversation')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
